### ISSUE TITLE
Entire client application freezes when Humio is unresponsive

### ISSUE THREAD

**Issue by lunkwill42** [Uninett/python-logging-humio#6]
python-logging-humio apparently froze our entire production application when Humio stopped responding.

Failing to log should never bring down an entire application like this. python-humio-logging should have some sort of timeout/failover so logging to Humio is suspended for some time if the connection fails.

Case in point, Ctrl-C in the frozen application gave this traceback:
```pytb
Traceback (most recent call last):
  File "/app/Argus/manage.py", line 23, in <module>
    main()
  File "/app/Argus/manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python3.10/site-packages/django/apps/config.py", line 124, in create
    mod = import_module(mod_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/site-packages/channels/apps.py", line 4, in <module>
    import daphne.server
  File "/usr/local/lib/python3.10/site-packages/daphne/server.py", line 7, in <module>
    twisted_loop = asyncio.new_event_loop()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 782, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 673, in new_event_loop
    return self._loop_factory()
  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 64, in __init__
    super().__init__(selector)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 54, in __init__
    logger.debug('Using selector: %s', selector.__class__.__name__)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1465, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/site-packages/humiologging/handlers/base.py", line 37, in emit
    self.send_to_humio(record)
  File "/usr/local/lib/python3.10/site-packages/humiologging/handlers/base.py", line 70, in send_to_humio
    client.ingest_json_data([recordblob])
  File "/usr/local/lib/python3.10/site-packages/humiolib/WebCaller.py", line 113, in wrapper
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/humiolib/HumioClient.py", line 635, in _ingest_json_data
    return self.webcaller.call_rest(
  File "/usr/local/lib/python3.10/site-packages/humiolib/WebCaller.py", line 47, in call_rest
    return self._make_request(verb, link, headers, data, files, stream, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/humiolib/WebCaller.py", line 87, in _make_request
    response = requests.request(
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
KeyboardInterrupt
Exception ignored in: <function BaseEventLoop.__del__ at 0x7fef1b664550>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 690, in __del__
    self.close()
  File "/usr/local/lib/python3.10/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 87, in close
    self._close_self_pipe()
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_ssock'````

**Comment by hmpf** [comment]
This should not happen from version 1.0.3 on. Exceptions on emit (except KeuboardInterrupt and SystemExit of course) are all caught.
